/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Seo = {
  _type: "seo";
  seoTitle: string;
  seoDescription: string;
};

export type Link = {
  _type: "link";
  label: string;
  url: string;
  isExternal?: boolean;
};

export type BlockContent = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    _key: string;
  } & TextColor | {
    href?: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
} | {
  asset: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
  };
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  _type: "image";
  _key: string;
}>;

export type RegisterVip = {
  _id: string;
  _type: "registerVip";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo: Seo;
  herobannerBgImage: {
    asset: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  herobannerTitle: string;
  formTitle: string;
  formButton: Link;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type BecomeAVip = {
  _id: string;
  _type: "becomeAVip";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo: Seo;
  heroBannerTitle: string;
  heroBannerBackgroundImage: {
    asset: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  vipDetailTitle: string;
  vipDetailDescription: string;
  vipDetailInfoTitle: string;
  vipDetailInfoPoints: Array<{
    icon: {
      asset: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      _type: "image";
    };
    title: string;
    description: string;
    _key: string;
  }>;
  vipDetailButton: Link;
  overviewTitle: string;
  overviewDescription: BlockContent;
  overviewCourseValidationNote: BlockContent;
};

export type Contact = {
  _id: string;
  _type: "contact";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo: Seo;
  heroBannerTitle: string;
  heroBannerBackgroundImage: {
    asset: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  formTitle: string;
  getInTouchHeading: string;
  getInTouchDescription: string;
  locationInfoTitle: string;
  locationMapUrl: string;
  physicalAddress: string;
  phoneNumber: string;
  email: string;
};

export type News = {
  _id: string;
  _type: "news";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo: Seo;
  heroBannerTitle: string;
  heroBannerBackgroundImage: {
    asset: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
};

export type About = {
  _id: string;
  _type: "about";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo: Seo;
  herobannerBgImage: {
    asset: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  herobannerTitle: string;
  aboutHeading: string;
  aboutContent: BlockContent;
  aboutImage: {
    asset: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  guidedByHeading: string;
  guidedByContent: BlockContent;
  guidedByImages: Array<{
    image: {
      asset: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      _type: "image";
    };
    name: string;
    designation: string;
    _key: string;
  }>;
  aboutPagePoints: Array<{
    heading: string;
    content: BlockContent;
    image: {
      asset: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      _type: "image";
    };
    _key: string;
  }>;
};

export type Home = {
  _id: string;
  _type: "home";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo: Seo;
  herobannerBgImage: {
    asset: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  herobannerHeading: string;
  herobannerSubHeading: string;
  herobannerTitle: string;
  herobannerSubTitle: string;
  herobannerButton1: Link;
  herobannerButton2: Link;
  upcomingCourseImage: {
    asset: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  upcomingCourseTitle: string;
  upcomingCourseButton: Link;
  whyUsBackgroundImage: {
    asset: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  whyUsHeading: string;
  whyUsContent: BlockContent;
  whyUsButton: Link;
  whyUsImages: Array<{
    image: {
      asset: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      _type: "image";
    };
    name: string;
    designation: string;
    _key: string;
  }>;
  ourCoursesHeading: string;
  ourCoursesContent: BlockContent;
  ourCoursesBgImage: {
    asset: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  continuingEducationBgImage: {
    asset: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  continuingEducationHeading: string;
  continuingEducationContent: BlockContent;
  becomeAVipBgImage: {
    asset: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  becomeAVipHeading: string;
  becomeAVipContent: BlockContent;
  becomeAVipButton: Link;
  solutionsBackgroundImage: {
    asset: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  solutionsHeading: string;
  solutionsContent: BlockContent;
  solutionsButton: Link;
  solutionsImage: {
    asset: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  providerBackgroundImage: {
    asset: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  providerHeading: string;
  providerContent: BlockContent;
  providerImage: {
    asset: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
};

export type Settings = {
  _id: string;
  _type: "settings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  headerLogo: {
    asset: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  headerLinks: Array<{
    _key: string;
  } & Link>;
  headerButton: string;
  headerButtonLinks: Array<{
    _key: string;
  } & Link>;
  footerLogo: {
    asset: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  footerLinkGroups: Array<{
    label: string;
    groupLinks: Array<{
      _key: string;
    } & Link>;
    _key: string;
  }>;
  contactPhone: string;
  contactEmail: string;
  contactDescription: string;
  socialMediaLinks: Array<{
    image: {
      asset: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      _type: "image";
    };
    url: string;
    isExternal?: boolean;
    _key: string;
  }>;
};

export type HighlightColor = {
  _type: "highlightColor";
  label?: string;
  value?: string;
};

export type TextColor = {
  _type: "textColor";
  label?: string;
  value?: string;
};

export type SimplerColor = {
  _type: "simplerColor";
  label?: string;
  value?: string;
};

export type MediaTag = {
  _id: string;
  _type: "media.tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: Slug;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = Seo | Link | BlockContent | RegisterVip | SanityImageCrop | SanityImageHotspot | BecomeAVip | Contact | News | About | Home | Settings | HighlightColor | TextColor | SimplerColor | MediaTag | Slug | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./sanity/lib/queries.ts
// Variable: settingsQuery
// Query: *[_id == 'settings' && _type == 'settings'][0]
export type SettingsQueryResult = {
  _id: "settings";
  _type: "settings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  headerLogo: {
    asset: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  headerLinks: Array<{
    _key: string;
  } & Link>;
  headerButton: string;
  headerButtonLinks: Array<{
    _key: string;
  } & Link>;
  footerLogo: {
    asset: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  footerLinkGroups: Array<{
    label: string;
    groupLinks: Array<{
      _key: string;
    } & Link>;
    _key: string;
  }>;
  contactPhone: string;
  contactEmail: string;
  contactDescription: string;
  socialMediaLinks: Array<{
    image: {
      asset: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      _type: "image";
    };
    url: string;
    isExternal?: boolean;
    _key: string;
  }>;
} | null;
// Variable: homePageQuery
// Query: *[_id == 'home' && _type == 'home'][0]
export type HomePageQueryResult = {
  _id: "home";
  _type: "home";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo: Seo;
  herobannerBgImage: {
    asset: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  herobannerHeading: string;
  herobannerSubHeading: string;
  herobannerTitle: string;
  herobannerSubTitle: string;
  herobannerButton1: Link;
  herobannerButton2: Link;
  upcomingCourseImage: {
    asset: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  upcomingCourseTitle: string;
  upcomingCourseButton: Link;
  whyUsBackgroundImage: {
    asset: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  whyUsHeading: string;
  whyUsContent: BlockContent;
  whyUsButton: Link;
  whyUsImages: Array<{
    image: {
      asset: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      _type: "image";
    };
    name: string;
    designation: string;
    _key: string;
  }>;
  ourCoursesHeading: string;
  ourCoursesContent: BlockContent;
  ourCoursesBgImage: {
    asset: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  continuingEducationBgImage: {
    asset: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  continuingEducationHeading: string;
  continuingEducationContent: BlockContent;
  becomeAVipBgImage: {
    asset: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  becomeAVipHeading: string;
  becomeAVipContent: BlockContent;
  becomeAVipButton: Link;
  solutionsBackgroundImage: {
    asset: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  solutionsHeading: string;
  solutionsContent: BlockContent;
  solutionsButton: Link;
  solutionsImage: {
    asset: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  providerBackgroundImage: {
    asset: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  providerHeading: string;
  providerContent: BlockContent;
  providerImage: {
    asset: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
} | null;
// Variable: aboutPageQuery
// Query: *[_id == 'about' && _type == 'about'][0]
export type AboutPageQueryResult = {
  _id: "about";
  _type: "about";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo: Seo;
  herobannerBgImage: {
    asset: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  herobannerTitle: string;
  aboutHeading: string;
  aboutContent: BlockContent;
  aboutImage: {
    asset: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  guidedByHeading: string;
  guidedByContent: BlockContent;
  guidedByImages: Array<{
    image: {
      asset: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      _type: "image";
    };
    name: string;
    designation: string;
    _key: string;
  }>;
  aboutPagePoints: Array<{
    heading: string;
    content: BlockContent;
    image: {
      asset: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      _type: "image";
    };
    _key: string;
  }>;
} | null;
// Variable: contactQuery
// Query: *[_id == 'contact' && _type == "contact"][0]
export type ContactQueryResult = {
  _id: "contact";
  _type: "contact";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo: Seo;
  heroBannerTitle: string;
  heroBannerBackgroundImage: {
    asset: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  formTitle: string;
  getInTouchHeading: string;
  getInTouchDescription: string;
  locationInfoTitle: string;
  locationMapUrl: string;
  physicalAddress: string;
  phoneNumber: string;
  email: string;
} | null;
// Variable: newsPageQuery
// Query: *[_id == "news" && _type == "news"][0]
export type NewsPageQueryResult = {
  _id: "news";
  _type: "news";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo: Seo;
  heroBannerTitle: string;
  heroBannerBackgroundImage: {
    asset: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
} | null;
// Variable: becomeAVipPageQuery
// Query: *[_id == "becomeAVip" && _type == "becomeAVip"][0]
export type BecomeAVipPageQueryResult = {
  _id: "becomeAVip";
  _type: "becomeAVip";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo: Seo;
  heroBannerTitle: string;
  heroBannerBackgroundImage: {
    asset: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  vipDetailTitle: string;
  vipDetailDescription: string;
  vipDetailInfoTitle: string;
  vipDetailInfoPoints: Array<{
    icon: {
      asset: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      _type: "image";
    };
    title: string;
    description: string;
    _key: string;
  }>;
  vipDetailButton: Link;
  overviewTitle: string;
  overviewDescription: BlockContent;
  overviewCourseValidationNote: BlockContent;
} | null;
// Variable: registerVipPageQuery
// Query: *[_id == "registerVip" && _type == "registerVip"][0]
export type RegisterVipPageQueryResult = {
  _id: "registerVip";
  _type: "registerVip";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo: Seo;
  herobannerBgImage: {
    asset: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  herobannerTitle: string;
  formTitle: string;
  formButton: Link;
} | null;
// Variable: coursesQuery
// Query: *[_type == 'courses' && 'NAS' in coursePlatforms] | order(orderRank) {  ...,  courseTag->}
export type CoursesQueryResult = Array<never>;
// Variable: newsQuery
// Query: {  "categories": *[_type == "newsCategory"]{    ...,    "count": count(*[_type == "newsDetails" && references(^._id)])  },  "newsList": *[_type == "newsDetails" && 'NAS' in newsPlatforms] | order(date desc){    ...,    newsCategory->{      ...    },    "plainContent": pt::text(content)  },  "totalNewsCount": count(*[_type == "newsDetails"])}
export type NewsQueryResult = {
  categories: Array<never>;
  newsList: Array<never>;
  totalNewsCount: number;
};
// Variable: newsDetailQuery
// Query: *[_type == "newsDetails" && slug.current == $slug][0]{    ...,}
export type NewsDetailQueryResult = null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "*[_id == 'settings' && _type == 'settings'][0]": SettingsQueryResult;
    "*[_id == 'home' && _type == 'home'][0]": HomePageQueryResult;
    "*[_id == 'about' && _type == 'about'][0]": AboutPageQueryResult;
    "*[_id == 'contact' && _type == \"contact\"][0]": ContactQueryResult;
    "*[_id == \"news\" && _type == \"news\"][0]": NewsPageQueryResult;
    "*[_id == \"becomeAVip\" && _type == \"becomeAVip\"][0]": BecomeAVipPageQueryResult;
    "*[_id == \"registerVip\" && _type == \"registerVip\"][0]": RegisterVipPageQueryResult;
    "*[_type == 'courses' && 'NAS' in coursePlatforms] | order(orderRank) {\n  ...,\n  courseTag->\n}": CoursesQueryResult;
    "\n{\n  \"categories\": *[_type == \"newsCategory\"]{\n    ...,\n    \"count\": count(*[_type == \"newsDetails\" && references(^._id)])\n  },\n\n  \"newsList\": *[_type == \"newsDetails\" && 'NAS' in newsPlatforms] | order(date desc){\n    ...,\n    newsCategory->{\n      ...\n    },\n    \"plainContent\": pt::text(content)\n  },\n\n  \"totalNewsCount\": count(*[_type == \"newsDetails\"])\n}\n": NewsQueryResult;
    "*[_type == \"newsDetails\" && slug.current == $slug][0]{\n    ...,\n}": NewsDetailQueryResult;
  }
}
