import type { Metadata } from "next";
import { Ubuntu_Sans } from "next/font/google";
import "./globals.css";

const ubuntuSans = Ubuntu_Sans({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-unbuntu-sans",
  style: ["normal", "italic"],
  preload: true,
});

export const metadata: Metadata = {
  title: "Nashville Auction School",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ubuntuSans.variable} antialiased font-unbuntu-sans`}>
        {children}
      </body>
    </html>
  );
}
